export const TRANSPORT_MODES = [
  { key: 'walk', label: 'Walk', icon: '🚶', color: '#10B981' },
  { key: 'cycle', label: 'Cycle', icon: '🚴', color: '#3B82F6' },
  { key: 'e-scooter', label: 'E-Scooter', icon: '🛴', color: '#8B5CF6' },
  { key: 'bus', label: 'Bus', icon: '🚌', color: '#F59E0B' },
  { key: 'train', label: 'Train', icon: '🚆', color: '#06B6D4' },
  { key: 'boat', label: 'Boat', icon: '⛴️', color: '#0EA5E9' },
  { key: 'plane', label: 'Plane', icon: '✈️', color: '#DC2626' },
  { key: 'drive', label: 'Drive', icon: '🚗', color: '#EF4444' },
] as const;

export const DEMO_QUICK_FILLS = [
  { label: '2km Cycle', distance: 2, mode: 'cycle' },
  { label: '5km Walk', distance: 5, mode: 'walk' },
  { label: '8km Bus', distance: 8, mode: 'bus' },
  { label: '12km Train', distance: 12, mode: 'train' },
  { label: '3km E-Scooter', distance: 3, mode: 'e-scooter' },
  { label: '15km Train', distance: 15, mode: 'train' },
];

export const SMART_ROUTES = [
  { label: 'RGU → City Centre', from: 'RGU Garthdee Campus', to: 'Union Square', distance: 4.2, mode: 'bus' },
  { label: 'RGU → Train Station', from: 'RGU Garthdee Campus', to: 'Aberdeen Train Station', distance: 3.8, mode: 'cycle' },
  { label: 'Bridge of Don → RGU', from: 'Bridge of Don', to: 'RGU Garthdee Campus', distance: 9.5, mode: 'bus' },
  { label: 'Dyce → City Centre', from: 'Dyce', to: 'Union Square', distance: 8.7, mode: 'train' },
  { label: 'Westhill → RGU', from: 'Westhill', to: 'RGU Garthdee Campus', distance: 11.2, mode: 'bus' },
  { label: 'Old Aberdeen → RGU', from: 'Old Aberdeen', to: 'RGU Garthdee Campus', distance: 5.8, mode: 'cycle' },
  { label: 'Cove Bay → City Centre', from: 'Cove Bay', to: 'Union Square', distance: 6.3, mode: 'bus' },
  { label: 'Kingswells → RGU', from: 'Kingswells', to: 'RGU Garthdee Campus', distance: 6.1, mode: 'cycle' },
];

export function getModeInfo(mode: string) {
  return TRANSPORT_MODES.find(m => m.key === mode) || TRANSPORT_MODES[0];
}

// Language translations
export const LANGUAGES: Record<string, { label: string; flag: string }> = {
  en: { label: 'English', flag: '🇬🇧' },
  es: { label: 'Español', flag: '🇪🇸' },
  fr: { label: 'Français', flag: '🇫🇷' },
  de: { label: 'Deutsch', flag: '🇩🇪' },
  zh: { label: '中文', flag: '🇨🇳' },
  ar: { label: 'العربية', flag: '🇸🇦' },
  pl: { label: 'Polski', flag: '🇵🇱' },
  ne: { label: 'नेपाली', flag: '🇳🇵' },
  ru: { label: 'Русский', flag: '🇷🇺' },
  uk: { label: 'Українська', flag: '🇺🇦' },
};

export type LangKey = keyof typeof LANGUAGES;

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    'hero.title': 'How did you commute today?',
    'hero.subtitle': 'Log your journey and see the impact vs. driving',
    'btn.compare': 'Compare & Log Journey',
    'btn.map': 'Select on Map',
    'btn.smartRoutes': 'Smart Routes',
    'label.distance': 'Distance (km)',
    'label.date': 'Date',
    'label.mode': 'Transport Mode',
    'label.start': 'Select start location',
    'label.end': 'Select destination',
    'nav.log': 'Log',
    'nav.stats': 'Stats',
    'results.saved': 'You saved',
    'results.drove': 'You drove — next time try a greener option!',
    'results.co2': 'CO₂ Saved',
    'results.time': 'Time',
    'results.calories': 'Extra Calories',
    'results.impact': 'Your Impact, Made Real',
    'results.health': 'Health Impact',
    'results.logAnother': 'Log Another',
    'results.dashboard': 'View Dashboard',
    'dash.co2saved': 'CO₂ Saved',
    'dash.calories': 'Calories Burned',
    'dash.streak': 'Current Streak',
    'dash.journeys': 'Total Journeys',
    'dash.weeklyGoal': 'Weekly CO₂ Goal',
    'dash.achievements': 'Achievements',
    'dash.leaderboards': 'Leaderboards',
    'dash.recentJourneys': 'Recent Journeys',
    'settings.darkMode': 'Dark Mode',
    'settings.accessibility': 'Accessibility',
    'settings.language': 'Language',
  },
  es: {
    'hero.title': '¿Cómo viajaste hoy?',
    'hero.subtitle': 'Registra tu viaje y ve el impacto vs. conducir',
    'btn.compare': 'Comparar y Registrar',
    'btn.map': 'Seleccionar en Mapa',
    'btn.smartRoutes': 'Rutas Inteligentes',
    'label.distance': 'Distancia (km)',
    'label.date': 'Fecha',
    'label.mode': 'Modo de Transporte',
    'label.start': 'Seleccionar origen',
    'label.end': 'Seleccionar destino',
    'nav.log': 'Registro',
    'nav.stats': 'Estadísticas',
    'results.saved': 'Ahorraste',
    'results.drove': '¡Conduciste — prueba una opción más verde!',
    'results.co2': 'CO₂ Ahorrado',
    'results.time': 'Tiempo',
    'results.calories': 'Calorías Extra',
    'results.impact': 'Tu Impacto, Hecho Real',
    'results.health': 'Impacto en Salud',
    'results.logAnother': 'Registrar Otro',
    'results.dashboard': 'Ver Panel',
    'dash.co2saved': 'CO₂ Ahorrado',
    'dash.calories': 'Calorías Quemadas',
    'dash.streak': 'Racha Actual',
    'dash.journeys': 'Viajes Totales',
    'dash.weeklyGoal': 'Meta Semanal CO₂',
    'dash.achievements': 'Logros',
    'dash.leaderboards': 'Clasificación',
    'dash.recentJourneys': 'Viajes Recientes',
    'settings.darkMode': 'Modo Oscuro',
    'settings.accessibility': 'Accesibilidad',
    'settings.language': 'Idioma',
  },
  fr: {
    'hero.title': 'Comment avez-vous voyagé aujourd\'hui?',
    'hero.subtitle': 'Enregistrez votre trajet et voyez l\'impact vs. conduire',
    'btn.compare': 'Comparer et Enregistrer',
    'btn.map': 'Sélectionner sur la Carte',
    'btn.smartRoutes': 'Itinéraires Intelligents',
    'label.distance': 'Distance (km)',
    'label.date': 'Date',
    'label.mode': 'Mode de Transport',
    'label.start': 'Sélectionner le départ',
    'label.end': 'Sélectionner la destination',
    'nav.log': 'Journal',
    'nav.stats': 'Stats',
    'results.saved': 'Vous avez économisé',
    'results.drove': 'Vous avez conduit — essayez une option plus verte!',
    'results.co2': 'CO₂ Économisé',
    'results.time': 'Temps',
    'results.calories': 'Calories Supplémentaires',
    'results.impact': 'Votre Impact, Rendu Réel',
    'results.health': 'Impact Santé',
    'results.logAnother': 'Enregistrer un Autre',
    'results.dashboard': 'Voir le Tableau de Bord',
    'dash.co2saved': 'CO₂ Économisé',
    'dash.calories': 'Calories Brûlées',
    'dash.streak': 'Série Actuelle',
    'dash.journeys': 'Trajets Totaux',
    'dash.weeklyGoal': 'Objectif Hebdomadaire CO₂',
    'dash.achievements': 'Réalisations',
    'dash.leaderboards': 'Classements',
    'dash.recentJourneys': 'Trajets Récents',
    'settings.darkMode': 'Mode Sombre',
    'settings.accessibility': 'Accessibilité',
    'settings.language': 'Langue',
  },
  de: {
    'hero.title': 'Wie bist du heute gependelt?',
    'hero.subtitle': 'Protokolliere deine Reise und sieh die Auswirkung vs. Autofahren',
    'btn.compare': 'Vergleichen & Protokollieren',
    'btn.map': 'Auf Karte Wählen',
    'btn.smartRoutes': 'Smarte Routen',
    'label.distance': 'Entfernung (km)',
    'label.date': 'Datum',
    'label.mode': 'Transportmittel',
    'label.start': 'Startort wählen',
    'label.end': 'Zielort wählen',
    'nav.log': 'Protokoll',
    'nav.stats': 'Statistiken',
    'results.saved': 'Du hast gespart',
    'results.drove': 'Du bist gefahren — versuch nächstes Mal eine grünere Option!',
    'results.co2': 'CO₂ Gespart',
    'results.time': 'Zeit',
    'results.calories': 'Extra Kalorien',
    'results.impact': 'Dein Impact, Real Gemacht',
    'results.health': 'Gesundheitsimpact',
    'results.logAnother': 'Weitere Protokollieren',
    'results.dashboard': 'Dashboard Anzeigen',
    'dash.co2saved': 'CO₂ Gespart',
    'dash.calories': 'Kalorien Verbrannt',
    'dash.streak': 'Aktuelle Serie',
    'dash.journeys': 'Gesamte Fahrten',
    'dash.weeklyGoal': 'Wöchentliches CO₂-Ziel',
    'dash.achievements': 'Erfolge',
    'dash.leaderboards': 'Bestenlisten',
    'dash.recentJourneys': 'Letzte Fahrten',
    'settings.darkMode': 'Dunkelmodus',
    'settings.accessibility': 'Barrierefreiheit',
    'settings.language': 'Sprache',
  },
  zh: { 'hero.title': '你今天怎么通勤的？', 'hero.subtitle': '记录你的旅程，查看与驾车的对比', 'btn.compare': '比较并记录', 'btn.map': '在地图上选择', 'btn.smartRoutes': '智能路线', 'label.distance': '距离 (km)', 'label.date': '日期', 'label.mode': '交通方式', 'label.start': '选择起点', 'label.end': '选择终点', 'nav.log': '记录', 'nav.stats': '统计', 'results.saved': '你节省了', 'results.co2': '节省CO₂', 'results.time': '时间', 'results.calories': '额外卡路里', 'settings.darkMode': '深色模式', 'settings.language': '语言' },
  ar: { 'hero.title': 'كيف تنقلت اليوم؟', 'hero.subtitle': 'سجل رحلتك وشاهد التأثير مقابل القيادة', 'btn.compare': 'قارن وسجل', 'btn.map': 'اختر على الخريطة', 'btn.smartRoutes': 'مسارات ذكية', 'label.distance': 'المسافة (كم)', 'label.date': 'التاريخ', 'label.mode': 'وسيلة النقل', 'nav.log': 'سجل', 'nav.stats': 'إحصائيات', 'settings.darkMode': 'الوضع المظلم', 'settings.language': 'اللغة' },
  pl: { 'hero.title': 'Jak dojeżdżałeś dzisiaj?', 'hero.subtitle': 'Zarejestruj podróż i zobacz wpływ vs. jazda samochodem', 'btn.compare': 'Porównaj i Zarejestruj', 'btn.map': 'Wybierz na Mapie', 'btn.smartRoutes': 'Inteligentne Trasy', 'label.distance': 'Odległość (km)', 'label.date': 'Data', 'label.mode': 'Środek Transportu', 'nav.log': 'Dziennik', 'nav.stats': 'Statystyki', 'settings.darkMode': 'Tryb Ciemny', 'settings.language': 'Język' },
  ne: {
    'hero.title': 'आज तपाईंले कसरी यात्रा गर्नुभयो?',
    'hero.subtitle': 'आफ्नो यात्रा दर्ता गर्नुहोस् र ड्राइभिङको तुलनामा प्रभाव हेर्नुहोस्',
    'btn.compare': 'तुलना गर्नुहोस् र यात्रा दर्ता गर्नुहोस्',
    'btn.map': 'मानचित्रमा छान्नुहोस्',
    'btn.smartRoutes': 'स्मार्ट मार्गहरू',
    'label.distance': 'दूरी (कि.मि.)',
    'label.date': 'मिति',
    'label.mode': 'परिवहन मोड',
    'label.start': 'सुरुवात स्थान छान्नुहोस्',
    'label.end': 'गन्तव्य स्थान छान्नुहोस्',
    'nav.log': 'लग',
    'nav.stats': 'तथ्याङ्क',
    'results.saved': 'तपाईंले बचत गर्नुभयो',
    'results.drove': 'तपाईंले गाडी चलाउनुभयो — अर्को पटक हरियो विकल्प रोज्नुहोस्!',
    'results.co2': 'CO₂ बचत',
    'results.time': 'समय',
    'results.calories': 'थप क्यालोरी',
    'results.impact': 'तपाईको प्रभाव, वास्तविक बनाइयो',
    'results.health': 'स्वास्थ्य प्रभाव',
    'results.logAnother': 'अर्को दर्ता गर्नुहोस्',
    'results.dashboard': 'ड्यासबोर्ड हेर्नुहोस्',
    'dash.co2saved': 'CO₂ बचत',
    'dash.calories': 'क्यालोरी जल्यो',
    'dash.streak': 'हालको स्ट्रिक',
    'dash.journeys': 'कुल यात्राहरू',
    'dash.weeklyGoal': 'साप्ताहिक CO₂ लक्ष्य',
    'dash.achievements': 'उपलब्धिहरू',
    'dash.leaderboards': 'लिडरबोर्डहरू',
    'dash.recentJourneys': 'हालका यात्राहरू',
    'settings.darkMode': 'डार्क मोड',
    'settings.accessibility': 'पहुँचयोग्यता',
    'settings.language': 'भाषा',
  },
  ru: {
    'hero.title': 'Как вы сегодня добирались?',
    'hero.subtitle': 'Запишите свою поездку и посмотрите влияние по сравнению с вождением',
    'btn.compare': 'Сравнить и записать',
    'btn.map': 'Выбрать на карте',
    'btn.smartRoutes': 'Умные маршруты',
    'label.distance': 'Расстояние (км)',
    'label.date': 'Дата',
    'label.mode': 'Способ передвижения',
    'label.start': 'Выберите место начала',
    'label.end': 'Выберите место назначения',
    'nav.log': 'Журнал',
    'nav.stats': 'Статистика',
    'results.saved': 'Вы сэкономили',
    'results.drove': 'Вы ехали на машине — в следующий раз попробуйте экологичный вариант!',
    'results.co2': 'CO₂ сохранено',
    'results.time': 'Время',
    'results.calories': 'Доп. калории',
    'results.impact': 'Ваше влияние в реальности',
    'results.health': 'Влияние на здоровье',
    'results.logAnother': 'Записать еще',
    'results.dashboard': 'Панель управления',
    'dash.co2saved': 'CO₂ сохранено',
    'dash.calories': 'Калории сожжены',
    'dash.streak': 'Текущая серия',
    'dash.journeys': 'Всего поездок',
    'dash.weeklyGoal': 'Еженедельная цель CO₂',
    'dash.achievements': 'Достижения',
    'dash.leaderboards': 'Таблицы лидеров',
    'dash.recentJourneys': 'Последние поездки',
    'settings.darkMode': 'Темная тема',
    'settings.accessibility': 'Доступность',
    'settings.language': 'Язык',
  },
  uk: {
    'hero.title': 'Як ви сьогодні добиралися?',
    'hero.subtitle': 'Запишіть свою поїздку та подивіться вплив у порівнянні з водінням',
    'btn.compare': 'Порівняти та записати',
    'btn.map': 'Вибрати на карті',
    'btn.smartRoutes': 'Розумні маршрути',
    'label.distance': 'Відстань (км)',
    'label.date': 'Дата',
    'label.mode': 'Спосіб пересування',
    'label.start': 'Виберіть місце початку',
    'label.end': 'Виберіть місце призначення',
    'nav.log': 'Журнал',
    'nav.stats': 'Статистика',
    'results.saved': 'Ви заощадили',
    'results.drove': 'Ви їхали на авто — наступного разу спробуйте екологічний варіант!',
    'results.co2': 'CO₂ заощаджено',
    'results.time': 'Час',
    'results.calories': 'Дод. калорії',
    'results.impact': 'Ваш вплив у реальності',
    'results.health': 'Вплив на здоров’я',
    'results.logAnother': 'Записати ще',
    'results.dashboard': 'Панель керування',
    'dash.co2saved': 'CO₂ заощаджено',
    'dash.calories': 'Калорії спалено',
    'dash.streak': 'Поточна серія',
    'dash.journeys': 'Всього поїздок',
    'dash.weeklyGoal': 'Тижнева ціль CO₂',
    'dash.achievements': 'Досягнення',
    'dash.leaderboards': 'Таблиці лідерів',
    'dash.recentJourneys': 'Останні поїздки',
    'settings.darkMode': 'Темна тема',
    'settings.accessibility': 'Доступність',
    'settings.language': 'Мова',
  },
};

export function t(key: string, lang: string): string {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
}
